# куда слушать
listen_addresses = '*'
port = 5432

# память
shared_buffers = 256MB
work_mem = 16MB

# WAL
wal_level = replica
max_wal_size = 1GB
min_wal_size = 80MB

# логирование
logging_collector = on
log_directory = 'log'
log_filename = 'postgresql.log'

# подключения
max_connections = 100
