services:
    fpm:
        environment: &production-environment
            APP_ENV: production
            APP_DEBUG: "false"
            LOG_LEVEL: warning

    setup:
        environment: *production-environment

    scheduler:
        environment: *production-environment

    queue:
        environment: *production-environment
