services:
    nginx:
        ports:
            - "${APP_VITE_PORT:-5173}:5173"

    setup:
        environment:
            APP_VITE_DEV: "true"

    vite:
        build:
            context: ./php
            args:
                APP_XDEBUG: "${APP_XDEBUG:-false}"
        user: "${HOST_UID}:${HOST_GID}"
        environment:
            APP_VITE_DEV: "true"
        networks:
            - edge
        depends_on:
            setup:
                condition: service_completed_successfully
        entrypoint: ["bash", "/usr/local/bin/scripts/vite_dev.sh"]
        volumes:
            - "${STORAGE_APP}:/var/www/html"
        restart: unless-stopped
