server {
    listen 80;

    server_name _;

    set $base /var/www/html;
	root $base/public;

    index index.php index.html;

    # Livewire serves dynamic JavaScript from routes like
    # /livewire-fd90339c/livewire.js?id=..., so bypass static .js locations.
    location ^~ /livewire {
        try_files $uri $uri/ /index.php?$query_string;
    }

    include nginxconfig.io/server/security.conf;
    include nginxconfig.io/server/general.conf;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $fastcgi_script_name =404;

        include fastcgi_params;

        fastcgi_pass fpm:9000;
        fastcgi_index index.php;

        fastcgi_param DOCUMENT_ROOT $realpath_root;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;

        # ВАЖНО: пробросить headers до Laravel/PHP
        fastcgi_param HTTP_X_REAL_IP $http_x_real_ip;
        fastcgi_param HTTP_X_FORWARDED_FOR $http_x_forwarded_for;
        fastcgi_param HTTP_X_FORWARDED_PROTO $http_x_forwarded_proto;
        fastcgi_param HTTP_X_FORWARDED_HOST $http_x_forwarded_host;
        fastcgi_param HTTP_X_FORWARDED_PORT $http_x_forwarded_port;

        fastcgi_param PHP_ADMIN_VALUE "open_basedir=$base/:/usr/lib/php/:/tmp/";
    }
}

map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}
